version: '3.8'

services:
  food-track:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: food-track
    restart: unless-stopped
    ports:
      - "3000:3000"
    # This creates a permanent bridge between the container and the server
    volumes:
      - food-track-data:/app/data

# This tells Docker to manage and protect this volume
volumes:
  food-track-data: